import 'dart:io';

import 'package:anas_localization/src/features/catalog/config/catalog_config.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('CatalogConfig auto_generate_dictionary', () {
    test('defaults to true', () {
      expect(CatalogConfig.defaults().autoGenerateDictionary, isTrue);
    });

    test('YAML round-trip preserves value', () async {
      final dir = await Directory.systemTemp.createTemp('anas_catalog_config_test_');
      addTearDown(() async {
        if (dir.existsSync()) {
          await dir.delete(recursive: true);
        }
      });

      final path = '${dir.path}/anas_catalog.yaml';
      final written = CatalogConfig.defaults().copyWith(autoGenerateDictionary: false);
      await CatalogConfig.writeConfig(path: path, config: written);

      final loaded = await CatalogConfig.load(path: path);
      expect(loaded.autoGenerateDictionary, isFalse);
    });
  });
}
