name: catalog_app
description: Internal Flutter web wrapper for the Anas catalog UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  anas_localization:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: any
flutter:
  uses-material-design: true
